<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Filekin.Core\Filekin.Core.csproj" />
    <ProjectReference Include="..\..\src\Filekin.Infrastructure.Windows\Filekin.Infrastructure.Windows.csproj" />
    <ProjectReference Include="..\..\src\Filekin.Mcp\Filekin.Mcp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
